[versions]
minecraft = "1.21.5"
loom = "1.10.1"
fabric-loader = "0.16.13"
fabric-api = "0.121.0+1.21.5"
fabric-language-kotlin = "1.13.2+kotlin.2.1.20"
koin = "4.0.4"
kotlinx-coroutines = "1.10.2"
kotlinx-serialization = "1.8.1"
ktor = "3.1.2"
renderer = "2.0.1"
modmenu = "14.0.0-rc.2"
ipaddress = "5.5.1"
kotlin = "2.1.20"
shadow = "9.0.0-beta12"
room = "2.7.0"
sqlite = "2.5.0"
ksp = "2.1.20-1.0.32"
androidx-lifecycle = "2.8.4"
compose-library = "0.0.+"
androidx-navigation = "2.9.0-alpha16"
compose-plugin = "1.8.0-beta02"
compose = "2025.04.00"
ktorfit = "2.5.1"

[libraries]
minecraft = { group = "com.mojang", name = "minecraft", version.ref = "minecraft" }
fabric-loader = { group = "net.fabricmc", name = "fabric-loader", version.ref = "fabric-loader" }
fabric-language-kotlin = { group = "net.fabricmc", name = "fabric-language-kotlin", version.ref = "fabric-language-kotlin" }
fabric-api = { group = "net.fabricmc.fabric-api", name = "fabric-api", version.ref = "fabric-api" }
koin-bom = { group = "io.insert-koin", name = "koin-bom", version.ref = "koin" }
koin-core = { group = "io.insert-koin", name = "koin-core" }
koin-compose-viewmodel = { group = "io.insert-koin", name = "koin-compose-viewmodel" }
kotlinx-coroutines = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-swing = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-jvm = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core-jvm", version.ref = "kotlinx-coroutines" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
ktor-client-contentnegotiation = { group = "io.ktor", name = "ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-logging = { group = "io.ktor", name = "ktor-client-logging", version.ref = "ktor" }
ktor-serialization-json = { group = "io.ktor", name = "ktor-serialization-kotlinx-json", version.ref = "ktor" }
renderer = { group = "io.github.0x3c50.renderer", name = "renderer-fabric", version.ref = "renderer" }
modmenu = { group = "com.terraformersmc", name = "modmenu", version.ref = "modmenu" }
ipaddress = { group = "com.github.seancfoley", name = "ipaddress", version.ref = "ipaddress" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-gradle-plugin = { group = "androidx.room", name = "room-gradle-plugin", version.ref = "room" }
sqlite-bundled = { group = "androidx.sqlite", name = "sqlite-bundled", version.ref = "sqlite" }
lifecycle-viewmodel = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-viewmodel", version.ref = "androidx-lifecycle" }
compose-library = { group = "cz.nejakejtomas", name = "ComposeLibrary", version.ref = "compose-library" }
navigation = { group = "org.jetbrains.androidx.navigation", name = "navigation-compose", version.ref = "androidx-navigation" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose" }
ktorfit = { group = "de.jensklingenberg.ktorfit", name = "ktorfit-lib", version.ref = "ktorfit" }


[plugins]
fabric-loom = { id = "fabric-loom", version.ref = "loom" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
jetbrainsCompose = { id = "org.jetbrains.compose", version.ref = "compose-plugin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
ktorfit = { id = "de.jensklingenberg.ktorfit", version.ref = "ktorfit" }